# Permalinks
permalink:           pretty

# Setup
title:               J-Max
tagline:             coder, writer, problem solver
url:                 http://j-max.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Max Barry
  url:              
  email:             jmax.barry@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
  Resources: '/resources'
